//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarberTb
    {
        public int IDBarber { get; set; }
        public string role { get; set; }
        public string name { get; set; }
    }
}
