//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsTb
    {
        public int iditem { get; set; }
        public string name { get; set; }
        public string amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
