//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarberBDEntities : DbContext
    {
        public BarberBDEntities()
            : base("name=BarberBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BarberTb> BarberTb { get; set; }
        public DbSet<ItemsTb> ItemsTb { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UsersTb> UsersTb { get; set; }
    }
}
